#!/bin/bash  
#SBATCH --job-name="Region_03"  
#SBATCH --output="Region_03.%j.%N.out"  
#SBATCH --partition=compute  
#SBATCH --nodes=2
#SBATCH --ntasks-per-node=24  
#SBATCH --export=ALL  
#SBATCH -t 00:05:00

module load intel/2015.2.164
module load mvapich2_ib

mpirun /home/rbarnes1/dist_pf/parallel_pit_fill.exe many @offloadall /oasis/scratch/comet/rbarnes1/temp_project/srtm_region/Region_03.layout /oasis/scratch/comet/rbarnes1/temp_project/srtm_output/Region_03
