#!/bin/bash  
#SBATCH --job-name="srtm_global_resampled"  
#SBATCH --output="srtm_global_resampled.%j.%N.out"  
#SBATCH --partition=compute  
#SBATCH --nodes=2
#SBATCH --ntasks-per-node=24  
#SBATCH --export=ALL  
#SBATCH -t 10:00:00

module load boost/1.55.0
module load intel/2015.2.164
module load mvapich2_ib

mpirun /home/rbarnes1/dist_pf/parallel_pit_fill.exe -V -H many @offloadall /oasis/scratch/comet/rbarnes1/temp_project/srtm_global/srtm_global_resampled.layout /oasis/scratch/comet/rbarnes1/temp_project/srtm_global_output/
