#!/bin/bash  
#SBATCH --job-name="srtm_global"  
#SBATCH --output="srtm_global.%j.%N.out"  
#SBATCH --partition=compute  
#SBATCH --nodes=2
#SBATCH --ntasks-per-node=24  
#SBATCH --export=ALL  
#SBATCH -t 04:00:00

module load intel/2015.2.164
module load mvapich2_ib

find /oasis/scratch/comet/rbarnes1/temp_project/srtm_global_output/ -type f -delete

mpirun /home/rbarnes1/dist_pf/parallel_pit_fill.exe many @evict /oasis/scratch/comet/rbarnes1/temp_project/srtm_global/srtm_global.layout /oasis/scratch/comet/rbarnes1/temp_project/srtm_global_output/%f.tif
