#!/bin/bash  
#SBATCH --job-name="srtm_weak_scaling_small"  
#SBATCH --output="srtm_weak_scaling_small.%j.%N.out"  
#SBATCH --partition=compute  
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=24  
#SBATCH --export=ALL  
#SBATCH -t 15:00:00

module load intel/2015.2.164
module load mvapich2_ib


find /oasis/scratch/comet/rbarnes1/temp_project/srtm_output/ -delete ; mkdir /oasis/scratch/comet/rbarnes1/temp_project/srtm_output/

mpirun -n 2  /home/rbarnes1/dist_pf/parallel_pit_fill.exe many @offloadall /oasis/scratch/comet/rbarnes1/temp_project/srtm_global/srtm-1.layout /oasis/scratch/comet/rbarnes1/temp_project/srtm_output/w1_%n.tif 

find /oasis/scratch/comet/rbarnes1/temp_project/srtm_output/ -delete ; mkdir /oasis/scratch/comet/rbarnes1/temp_project/srtm_output/

mpirun -n 3  /home/rbarnes1/dist_pf/parallel_pit_fill.exe many @offloadall /oasis/scratch/comet/rbarnes1/temp_project/srtm_global/srtm-2.layout /oasis/scratch/comet/rbarnes1/temp_project/srtm_output/w2_%n.tif 

find /oasis/scratch/comet/rbarnes1/temp_project/srtm_output/ -delete ; mkdir /oasis/scratch/comet/rbarnes1/temp_project/srtm_output/

mpirun -n 5  /home/rbarnes1/dist_pf/parallel_pit_fill.exe many @offloadall /oasis/scratch/comet/rbarnes1/temp_project/srtm_global/srtm-4.layout /oasis/scratch/comet/rbarnes1/temp_project/srtm_output/w4_%n.tif 

find /oasis/scratch/comet/rbarnes1/temp_project/srtm_output/ -delete ; mkdir /oasis/scratch/comet/rbarnes1/temp_project/srtm_output/

mpirun -n 9  /home/rbarnes1/dist_pf/parallel_pit_fill.exe many @offloadall /oasis/scratch/comet/rbarnes1/temp_project/srtm_global/srtm-8.layout /oasis/scratch/comet/rbarnes1/temp_project/srtm_output/w8_%n.tif 

find /oasis/scratch/comet/rbarnes1/temp_project/srtm_output/ -delete ; mkdir /oasis/scratch/comet/rbarnes1/temp_project/srtm_output/

mpirun -n 17 /home/rbarnes1/dist_pf/parallel_pit_fill.exe many @offloadall /oasis/scratch/comet/rbarnes1/temp_project/srtm_global/srtm-16.layout /oasis/scratch/comet/rbarnes1/temp_project/srtm_output/w16_%n.tif

find /oasis/scratch/comet/rbarnes1/temp_project/srtm_output/ -delete ; mkdir /oasis/scratch/comet/rbarnes1/temp_project/srtm_output/

mpirun -n 24 /home/rbarnes1/dist_pf/parallel_pit_fill.exe many @offloadall /oasis/scratch/comet/rbarnes1/temp_project/srtm_global/srtm-23.layout /oasis/scratch/comet/rbarnes1/temp_project/srtm_output/w23_%n.tif

find /oasis/scratch/comet/rbarnes1/temp_project/srtm_output/ -delete ; mkdir /oasis/scratch/comet/rbarnes1/temp_project/srtm_output/