#!/bin/bash  
#SBATCH --job-name="pamap_pan"  
#SBATCH --output="pamap_pan.%j.%N.out"  
#SBATCH --partition=compute  
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=24  
#SBATCH --export=ALL  
#SBATCH -t 01:30:00

module load boost/1.55.0
module load intel/2015.2.164
module load mvapich2_ib

mpirun ./parallel_pit_fill.exe many @offloadall /oasis/scratch/comet/rbarnes1/temp_project/pamap/pan_tiles_small.layout /oasis/scratch/comet/rbarnes1/temp_project/pan_output/              # Run the MPI executable named "a.out"